name: Deploy to Firebase
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run install
        uses: borales/actions-yarn@v3
        with:
          cmd: install # will run `yarn install` command
      - name: Add secrets
        run: |
          sed -i "s\API_KEY\${{ secrets.API_KEY }}\g" src/app/secrets.ts.template
          sed -i "s\AUTH_DOMAIN\${{ secrets.AUTH_DOMAIN }}\g" src/app/secrets.ts.template
          sed -i "s\DATABASE_URL\${{ secrets.DATABASE_URL }}\g" src/app/secrets.ts.template
          sed -i "s\PROJECT_ID\${{ secrets.PROJECT_ID }}\g" src/app/secrets.ts.template
          sed -i "s\STORAGE_BUCKET\${{ secrets.STORAGE_BUCKET }}\g" src/app/secrets.ts.template
          sed -i "s\APP_ID\${{ secrets.APP_ID }}\g" src/app/secrets.ts.template
      - name: Rename and move secrets.ts.template to secrets.ts
        run: mv src/app/secrets.ts.template src/app/secrets.ts
      - name: Build
        run: npx ng build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
